name = "vpsai"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables will go here

[[kv_namespaces]]
binding = "vpsai_kv"
id = "63e333fd63a64589a3faf57d48598cbe"

[[r2_buckets]]
binding = "vpsai_r2"
bucket_name = "ec4eb45ce5f23208803529f2e163b4db"

[assets]
directory = "./public"
binding = "ASSETS"
