name = "vpsai"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables will go here

[[kv_namespaces]]
binding = "vpsai_kv"
id = "26ff9ef4fcce4323a96c102d6bf5d52b"

[[r2_buckets]]
binding = "vpsai_r2"
bucket_name = "vpsia"

[assets]
directory = "./public"
binding = "ASSETS"
