name = "vpsai"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables will go here

[[kv_namespaces]]
binding = "vpsai_kv"
id = "4430ae38f40d4fe1b7359c9a596f4a05"

[[r2_buckets]]
binding = "vpsai_r2"
bucket_name = "vpsai"

[assets]
directory = "./public"
binding = "ASSETS"
